# Additional configuration options for `cargo clippy`.
# https://doc.rust-lang.org/clippy/configuration.html

# https://doc.rust-lang.org/clippy/lint_configuration.html#allow-unwrap-in-tests
allow-unwrap-in-tests = true

# https://doc.rust-lang.org/clippy/lint_configuration.html#doc-valid-idents
doc-valid-idents = [".."]
