[package]
name = "intrval"
version = "0.1.3"
description = "Generic intervals (ranges) library"
license = "MIT OR Apache-2.0"
repository = "https://github.com/tsionyx/intrval"
edition = "2021"
keywords = ["interval", "bounds", "math", "no-std"]
categories = ["science", "data-structures"]
authors = []
rust-version = "1.71"
readme = "README.md"
exclude = [
    ".gitignore",
    ".github/",
    ".cargo/",
    ".clippy.toml",
    "examples/",
    "proptest-regressions/",
]


[dependencies.rustversion]
version = "1.0"
default-features = false

[dependencies.serde]
version = "1.0.228"
default-features = false
features = ["derive"]
optional = true

[dependencies.proptest]
version = "~1.7"  # constrained to 1.7.x for MSRV compatibility
default-features = false
features = ["std"]
optional = true

[dependencies.rand]
version = "~0.9.2"
default-features = false
features = ["small_rng"]
optional = true


[dev-dependencies]
serde_json = "1.0.140"
ordered-float = { version = "5.0", default-features = false }


[features]
default = []

# Could require some extra `Clone` bounds.
# By default is disabled and emulated with `Interval::Closed((x, x))`.
singleton = []
serde = ["dep:serde"]
arbitrary = [
    "dep:proptest",

    # do not include this feature intentionally to avoid
    # adding another `proptest` dependency with `default-features=true`
    #"ordered-float/proptest"
]
random = ["dep:rand"]


[lints.rust]
# https://doc.rust-lang.org/nightly/cargo/reference/manifest.html#the-lints-section

# do not warn on older Rust versions
unknown_lints = "allow"

# The following list was generated with the command:
#   $ rustc -W help | grep ' allow ' | awk '{print $1}' | tr - _ | sort | xargs -I{} echo '{} = "warn"' | xclip -sel clip
#
# It is also available for the latest version of rustc at:
#   https://doc.rust-lang.org/rustc/lints/listing/allowed-by-default.html
absolute_paths_not_starting_with_crate = "warn"
ambiguous_negative_literals = "warn"
closure_returning_async_block = "warn"
deprecated_in_future = "warn"
deprecated_safe_2024 = "warn"
deref_into_dyn_supertrait = "warn"
# do not warn about using old `expr` in macros
edition_2024_expr_fragment_specifier = "allow"
elided_lifetimes_in_paths = "warn"
explicit_outlives_requirements = "warn"
ffi_unwind_calls = "warn"
fuzzy_provenance_casts = "warn"
if_let_rescope = "warn"
impl_trait_overcaptures = "warn"
impl_trait_redundant_captures = "warn"
keyword_idents_2018 = "warn"
keyword_idents_2024 = "warn"
let_underscore_drop = "warn"
linker_messages = "warn"
lossy_provenance_casts = "warn"
macro_use_extern_crate = "warn"
meta_variable_misuse = "warn"
missing_abi = "warn"
missing_copy_implementations = "warn"
missing_debug_implementations = "warn"
missing_docs = "warn"
missing_unsafe_on_extern = "warn"
multiple_supertrait_upcastable = "warn"
must_not_suspend = "warn"
non_ascii_idents = "warn"
non_exhaustive_omitted_patterns = "warn"
non_local_definitions = "warn"
redundant_imports = "warn"
redundant_lifetimes = "warn"
rust_2021_incompatible_closure_captures = "warn"
rust_2021_incompatible_or_patterns = "warn"
rust_2021_prefixes_incompatible_syntax = "warn"
rust_2021_prelude_collisions = "warn"
rust_2024_guarded_string_incompatible_syntax = "warn"
rust_2024_incompatible_pat = "warn"
rust_2024_prelude_collisions = "warn"
single_use_lifetimes = "warn"
supertrait_item_shadowing_definition = "warn"
supertrait_item_shadowing_usage = "warn"
tail_expr_drop_order = "warn"
trivial_casts = "warn"
trivial_numeric_casts = "warn"
unit_bindings = "warn"
unnameable_types = "warn"
# conflicts with the `clippy::redundant_pub_crate`
unreachable_pub = "allow"
unsafe_attr_outside_unsafe = "warn"
unsafe_code = "deny"
unsafe_op_in_unsafe_fn = "warn"
unstable_features = "warn"
# TODO: "warn" after fixing false-positive detecting
#  no usage of [dev-dependencies] that are used in examples
#  https://github.com/rust-lang/rust/issues/95513
unused_crate_dependencies = "allow"
unused_extern_crates = "warn"
unused_import_braces = "warn"
unused_lifetimes = "warn"
unused_macro_rules = "warn"
unused_qualifications = "warn"
unused_results = "warn"
variant_size_differences = "warn"

[lints.clippy]
# https://doc.rust-lang.org/clippy/lints.html
correctness = { level = "deny", priority = -1 }
suspicious = { level = "deny", priority = -2 }
complexity = { level = "warn", priority = -3 }
perf = { level = "warn", priority = -3 }
style ={ level = "warn", priority = -4 }
pedantic = { level = "warn", priority = -4 }
cargo = { level = "warn", priority = -5 }
nursery = { level = "warn", priority = -5 }

#
# === INDIVIDUAL LINT OVERRIDES ===
#
# set "allow" or "deny" for individual lints globally here:
mem_forget = "deny"
#
# The following are the "resriction" lints that are useful to warn about in most codebases.
# To check for other "restriction" lints, see the "RESTRICTION LINTS" section below for instructions.
#
absolute_paths = "warn"
as_conversions = "warn"
assertions_on_result_states = "warn"
dbg_macro = "warn"
else_if_without_else = "warn"
missing_docs_in_private_items = "warn"
return_and_then = "warn"
renamed_function_params = "warn"
semicolon_outside_block = "warn"
# It is better to allow `unwrap` in tests and examples before using the following lint:
unwrap_used = "warn"
# - Place this in the root module of your crate to allow `unwrap` in tests:
#   `#![cfg_attr(test, allow(clippy::unwrap_used))]`;
#   Better way is to set `allow-unwrap-in-tests = true` in _clippy.toml_ file;
# - In the standalone tests and examples, the usual `#![allow(clippy::unwrap_used)]` can be used.

#
# === RESTRICTION LINTS ===
#
# The "restriction" lints are very noisy, so we selectively "warn" some of them here.
# To analyze the codebase against the highest level of scrutiny
# (with all "restriction" lints enabled), uncomment the lines below:
#
#restriction = { level = "warn", priority = -6 }
#blanket_clippy_restriction_lints = "allow"
#
# Then use the following commd to generate the list of allowed lints:
#   $ cargo clippy --all-features --workspace --all-targets 2>&1 |\
#     grep -oP 'to override `-W clippy::restriction` add `#\[allow\(clippy::\K([^\)]+)' |\
#     sort | uniq | xargs -I{} echo '{} = "allow"' | xclip -sel clip
#
# Paste the output below to selectively allow some of the "restriction" lints.
#
# Then you can comment each line one by one to see the effect of enabling the lint.
# This way you can gradually increase the level of scrutiny of your codebase
# by pinning some of the lints with "warn" level in the overrides section above.
